apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: maximusmaxi/frontend:{{ .Values.frontend.version }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /app  # Mount path where the ConfigMap data will be available
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: frontend-cm0 