apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processor
  labels:
    app: image-processor
spec:
  replicas: {{ .Values.imageprocessor.replicaCount }}
  selector:
    matchLabels:
      app: image-processor
  template:
    metadata:
      labels:
        app: image-processor
    spec:
      containers:
        - name: image-processor
          image: maximusmaxi/image-processor:{{ .Values.imageprocessor.version }}
          ports:
            - containerPort: 5000